name: Deploy ESP32 Sensor Server

on:
  push:
    branches: [main, production]
  pull_request:
    branches: [main]
  workflow_dispatch:  # Allow manual triggers

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: esp32-sensor-server
  ECS_SERVICE: esp32-sensor-service
  ECS_CLUSTER: esp32-cluster

jobs:
 
  build-and-deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/production'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Get secrets from AWS Secrets Manager
        id: get-secrets
        run: |
          # Get MongoDB connection string
          MONGO_SECRET=$(aws secretsmanager get-secret-value \
            --secret-id "mongo" \
            --query SecretString --output text)

          # Get MQTT credentials
          MQTT_SECRET=$(aws secretsmanager get-secret-value \
          --secret-id "mqtt" \
          --query SecretString --output text)

          # Parse and export secrets (they should be JSON format)
          echo "MONGO_CONNECTION_STRING=$(echo $MONGO_SECRET | jq -r '.connectionString')" >> $GITHUB_ENV
          echo "MONGO_DATABASE=$(echo $MONGO_SECRET | jq -r '.database')" >> $GITHUB_ENV
          echo "MQTT_HOST=$(echo $MQTT_SECRET | jq -r '.host')" >> $GITHUB_ENV
          echo "MQTT_USERNAME=$(echo $MQTT_SECRET | jq -r '.username')" >> $GITHUB_ENV
          echo "MQTT_PASSWORD=$(echo $MQTT_SECRET | jq -r '.password')" >> $GITHUB_ENV

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Build Docker image
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .

          # Push to ECR
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }} # For Ubuntu, this is 'ubuntu'
          EC2_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Setup SSH
          mkdir -p ~/.ssh
          echo "$EC2_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "$EC2_HOST" >> ~/.ssh/known_hosts

          # SSH into EC2 and run deployment commands
          # Secrets are passed directly from the GitHub runner's environment
          ssh -i ~/.ssh/id_rsa "$EC2_USER@$EC2_HOST" "
            set -e # Exit script on any error

            echo 'Logging into AWS ECR...'
            aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

            echo 'Pulling the latest Docker image...'
            docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

            echo 'Stopping and removing old container...'
            docker stop esp32-sensor-server || true
            docker rm esp32-sensor-server || true

            echo 'Starting new container with secrets...'
            docker run -d \
              --name esp32-sensor-server \
              --restart unless-stopped \
              -p 3000:3000 \
              -e MONGO_CONNECTION_STRING='${{ env.MONGO_CONNECTION_STRING }}' \
              -e MONGO_DATABASE='${{ env.MONGO_DATABASE }}' \
              -e MQTT_HOST='${{ env.MQTT_HOST }}' \
              -e MQTT_USERNAME='${{ env.MQTT_USERNAME }}' \
              -e MQTT_PASSWORD='${{ env.MQTT_PASSWORD }}' \
              -e NODE_ENV=production \
              -e PORT=3000 \
              $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

            echo 'Cleaning up old images...'
            docker image prune -f

            echo '✅ Deployment completed successfully!'
          "

      - name: Verify deployment
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          # Wait for service to be ready
          sleep 30

          # Check if service is responding
          if curl -f http://$EC2_HOST:3000/health; then
            echo "✅ Service is healthy and responding"
          else
            echo "❌ Service health check failed"
            exit 1
          fi

      - name: Notify deployment status
        if: always()
        run: |
          if [ ${{ job.status }} == 'success' ]; then
            echo "🚀 Deployment to ${{ github.ref_name }} completed successfully!"
          else
            echo "❌ Deployment failed"
          fi